USE `sma_admin`;

INSERT INTO `account` (`email`, `password`, `firstname`, `lastname`, `status`) VALUES
('{{EMAIL}}', '$2y$10$iKbbKC6.DuViU7Snz6Bn4uf1y8cXBx6pCXbJfJLxk77kKNQXw5tc.', 'Admin', 'Admin', 'enabled');

USE `sma_common`;

INSERT INTO `contact` (`firstname`, `lastname`, `email`, `id_account`, `is_account`) VALUES
('Admin', 'Admin', '{{EMAIL}}', 1, 1);

INSERT INTO `letter_template` (`id_account`, `category`, `title`, `description`, `data_type`, `data_type_filters`, `target_type`, `search_data`, `bean`) VALUES
(1, 'common', 'Relance de facture impayée', '', 'invoice', 'overdue', 'both', 'relance de facture impayee ', 'O:19:"Sma\\Bean\\LetterBean":20:{s:7:"\0*\0dear";s:0:"";s:7:"\0*\0body";s:302:"Nous vous informons que votre facture {{ doc.code }} devait être payée depuis le {{ doc.date_validite }}. Nous vous serions gré de bien vouloir solder la somme de {{ doc.total_ttc }} correspondant à cette facture. \r\n\r\nVeuillez agréer, {{ dest.cher }}, l\'expression de nos sentiments les meilleurs.";s:12:"\0*\0signature";s:0:"";s:11:"\0*\0markdown";b:1;s:15:"\0*\0attachLetter";b:0;s:38:"\0Osf\\Bean\\AbstractBean\0lastBuildedHash";N;s:7:"\0*\0libs";a:3:{s:7:"Objet :";s:37:"Votre facture impayée {{ doc.code }}";s:6:"Attn :";s:22:"{{ dest.nom_complet }}";s:2:" :";s:0:"";}s:8:"\0*\0title";s:37:"Votre facture impayée {{ doc.code }}";s:10:"\0*\0subject";N;s:19:"\0*\0displayCreatedBy";b:1;s:15:"\0*\0confidential";b:1;s:7:"\0*\0date";N;s:8:"\0*\0place";N;s:9:"\0*\0config";N;s:9:"\0*\0status";s:7:"created";s:11:"\0*\0provider";N;s:12:"\0*\0recipient";N;s:5:"\0*\0id";N;s:11:"\0*\0template";N;s:15:"\0*\0attachmentId";N;}'),
(1, 'common', 'Changement d\'adresse', '', 'recipient', 'status_created,status_sent,status_read', 'both', 'changement d\'adresse ', 'O:19:"Sma\\Bean\\LetterBean":20:{s:7:"\0*\0dear";s:0:"";s:7:"\0*\0body";s:124:"Veuillez noter notre nouvelle adresse : \r\n\r\n* **{{ exp.adresse }}**\r\n\r\nVeuillez agréer, {{ dest.cher }}, nos salutations...";s:12:"\0*\0signature";s:0:"";s:11:"\0*\0markdown";b:1;s:15:"\0*\0attachLetter";b:0;s:38:"\0Osf\\Bean\\AbstractBean\0lastBuildedHash";N;s:7:"\0*\0libs";a:2:{s:7:"Objet :";s:40:"{{ exp.titre }} change d\'adresse postale";s:2:" :";s:0:"";}s:8:"\0*\0title";s:40:"{{ exp.titre }} change d\'adresse postale";s:10:"\0*\0subject";N;s:19:"\0*\0displayCreatedBy";b:1;s:15:"\0*\0confidential";b:0;s:7:"\0*\0date";N;s:8:"\0*\0place";N;s:9:"\0*\0config";N;s:9:"\0*\0status";s:7:"created";s:11:"\0*\0provider";N;s:12:"\0*\0recipient";N;s:5:"\0*\0id";N;s:11:"\0*\0template";N;s:15:"\0*\0attachmentId";N;}'),
(1, 'mine', 'Bienvenue (nouveau client)', '', 'recipient', '', 'email', 'bienvenue (nouveau client) ', 'O:19:"Sma\\Bean\\LetterBean":20:{s:7:"\0*\0dear";s:0:"";s:7:"\0*\0body";s:300:"Nous sommes heureux de vous compter parmi nos clients. Vous disposez d\'un espace pour consulter vos documents (lettres, devis, commandes et factures) et compléter les informations vous concernant : \r\n\r\n* [L\'espace client de {{ dest.titre }}]({{ dest.login_url }})\r\n\r\nEn restant à votre disposition.";s:12:"\0*\0signature";s:0:"";s:11:"\0*\0markdown";b:1;s:15:"\0*\0attachLetter";b:0;s:38:"\0Osf\\Bean\\AbstractBean\0lastBuildedHash";N;s:7:"\0*\0libs";a:2:{s:7:"Objet :";s:49:"Bienvenue chez {{ exp.titre }}, {{ dest.cher }} !";s:2:" :";s:0:"";}s:8:"\0*\0title";s:49:"Bienvenue chez {{ exp.titre }}, {{ dest.cher }} !";s:10:"\0*\0subject";s:49:"Bienvenue chez {{ exp.titre }}, {{ dest.cher }} !";s:19:"\0*\0displayCreatedBy";b:1;s:15:"\0*\0confidential";b:0;s:7:"\0*\0date";N;s:8:"\0*\0place";N;s:9:"\0*\0config";N;s:9:"\0*\0status";s:7:"created";s:11:"\0*\0provider";N;s:12:"\0*\0recipient";N;s:5:"\0*\0id";N;s:11:"\0*\0template";N;s:15:"\0*\0attachmentId";N;}'),
(1, 'common', 'Envoi d\'un devis, commande ou facture', '', 'invoices', 'status_created,status_sent,status_read', 'email', 'envoi d\'un devis, commande ou facture ', 'O:19:"Sma\\Bean\\LetterBean":20:{s:7:"\0*\0dear";s:0:"";s:7:"\0*\0body";s:692:"Votre {{ doc.type ~ \' \' ~ doc.code }} pour un montant de {{ doc.total_ttc }}{% if doc.franchise_tva == false %} TTC{% endif %} est disponible. \r\n{% if doc.type == \'devis\' %}Vous avez jusqu\'au {{ doc.date_validite }} pour répondre à cette offre.{% endif %}\r\n{% if doc.type == \'commande\' %}Veuillez noter que cette offre est valable jusqu\'au {{ doc.date_validite }}.{% endif %}\r\n{% if doc.type == \'facture\' %}La date limite de paiement est fixée au {{ doc.date_validite }}.{% endif %}\r\n\r\n* **[Accéder à votre espace sécurisé]({{ dest.login_url }})**\r\n* **[Télécharger votre {{ doc.type ~ \' \' ~ doc.code }}]({{ doc.url }})**\r\n\r\nEn vous souhaitant bonne réception.\r\n\r\nBien cordialement,";s:12:"\0*\0signature";s:0:"";s:11:"\0*\0markdown";b:1;s:15:"\0*\0attachLetter";b:0;s:38:"\0Osf\\Bean\\AbstractBean\0lastBuildedHash";N;s:7:"\0*\0libs";a:3:{s:7:"Objet :";s:35:"Votre {{ doc.type }} {{ doc.code }}";s:18:"A l\'attention de :";s:22:"{{ dest.nom_complet }}";s:2:" :";s:0:"";}s:8:"\0*\0title";s:35:"Votre {{ doc.type }} {{ doc.code }}";s:10:"\0*\0subject";s:35:"Votre {{ doc.type }} {{ doc.code }}";s:19:"\0*\0displayCreatedBy";b:1;s:15:"\0*\0confidential";b:0;s:7:"\0*\0date";N;s:8:"\0*\0place";N;s:9:"\0*\0config";N;s:9:"\0*\0status";s:7:"created";s:11:"\0*\0provider";N;s:12:"\0*\0recipient";N;s:5:"\0*\0id";N;s:11:"\0*\0template";N;s:15:"\0*\0attachmentId";N;}');
