<?php

use Osf\Pdf\Document\Bean\BaseDocumentBean as BDB;
use Osf\Exception\ArchException;
use Osf\Stream\Text as T;
use Osf\Helper\DateTime as DT;
//use Osf\Stream\Text;
//use Sma\Container;
//use Osf\Helper\Mysql;

switch (true) {
    case in_array($row['status'], [BDB::STATUS_SENT, BDB::STATUS_READ]) && $row['total_ttc'] >= 0 : 
        $status = 'warning';
        $statusLabel = H::html(__("A régler"))->addCssClasses(['label', 'label-warning']);
        $color = 'yellow';
        $important = true;
        break;
    case in_array($row['status'], [BDB::STATUS_SENT, BDB::STATUS_READ]) && $row['total_ttc'] < 0 : 
        $status = 'default';
        $statusLabel = H::html(__("A percevoir"))->addCssClasses(['label', 'label-default']);
        $color = 'gray';
        $important = true;
        break;
    case $row['status'] === BDB::STATUS_PROCESSED && $row['total_ttc'] >= 0 : 
        $status = 'success';
        $statusLabel = H::html(__("Réglé"))->addCssClasses(['label', 'label-success']);
        $color = 'green';
        $important = false;
        break;
    case $row['status'] === BDB::STATUS_PROCESSED && $row['total_ttc'] < 0 : 
        $status = 'info';
        $statusLabel = H::html(__("Perçu"))->addCssClasses(['label', 'label-info']);
        $color = 'blue';
        $important = false;
        break;
    default : 
        throw new ArchException('Unknown status [' . $row['statuts'] . ']');
}

/* @var $bean \Sma\Bean\InvoiceBean */
$bean = unserialize($row['bean']);
$icon = H::icon('file-pdf-o', null, $color);
$lines = [
    $icon . '&nbsp;&nbsp;' . H::html($row['code'], $important ? 'strong' : 'span') .
    H::html(T::currencyFormat($row['total_ttc']) . ' TTC')->addCssClass('pull-right'),
    H::html(__("Date limite :")) . ' ' . H::html(T::formatDate($bean->getDateValidity()))->addCssClass('text-' . DT::getDateColor($bean->getDateValidity()), $important) .
    H::html($statusLabel)->escape(false)->addCssClass('pull-right')
];
return H::grid()->auto($lines);
