## ADMIN : only admins
## PUBLIC : everyone
## LOGGED : logged in users
## XXX : users in group XXX
## name@host.com : a user

controller: PUBLIC
action:
    error:
    init:
    tick:
    upload:
    notfound: 
    check: 
    ac: LOGGED
    search: LOGGED
    rmnot: LOGGED
    msg: 
