<?php 

echo H::alert(
        __("Hi contributors :)"),
        __("Use this page to test your forms.")
        );

//$forms = H::get('forms');
//foreach ($forms as $form) {
//    echo H::form($form);
//}
//echo H::form(DB::getTicketTable()->getForm()->displayLabels(false)->setTitle('Ticket'));
//echo H::form(DB::getTicketTable()->getForm()->displayLabels(true)->setTitle('Nouveau ticket'));
//echo H::box("Contact", H::form(DB::getContactTable()->getForm()->displayLabels()->setHorizontal()));
//echo H::box("Entreprise", H::form(DB::getCompanyTable()->getForm()->displayLabels()->setHorizontal()));
