<?php 

//include __DIR__ . '/_menu_edit.phtml';

// Modal d'ajout d'un nouveau destinataire
echo H::modal(
    'mform',
    __("Nouveau destinataire"), 
    H::html('', 'div', ['id' => 'medit']),
    clone H::button(__("Fermer"))->statusDefault()->setAttribute('data-dismiss', 'modal') . 
    clone H::button(__("Ajouter"))
            ->setAttribute('type', 'submit')
            ->setAttribute('onclick', "\$.ajaxCall(\$('#fedit'),'#medit',false,true);")
            ->statusPrimary());

echo H::form(H::get('form'))->setAttribute('novalidate');

// Affichage du preview
if (H::get('preview')) {
?>

<div id="fullwin" style="display: none; position: absolute;width: 100%; height: 100%; left: 0; top: 0; z-index: 99999; background: black;"><?php echo H::button(__("Retour"))->icon('caret-left')->flat()->sizeLarge()->setAttribute('style', 'width: 100%; background: #111; border: 0;color: #fff;font-weight: 600;')->setAttribute('onclick', '$(this).parent().hide();'); ?><i style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);" class="fa fa-hourglass-half"></i></div>
<script>
var currentState = history.state;
history.pushState(currentState, 'edit');
$('#fullwin').show();window.scrollTo(0,0);
$('#fullwin > i').replaceWith('<iframe id="icontainer" style="width: 100%; height: 100%; border: 0;" src="/pdfjs/web/viewer.html?file=/invoice/edit/render/doc.pdf"></iframe>');
window.onpopstate = function(e) {
  $('#fullwin').hide();
};
</script>

<?php 
}

// Affichage du lien si pas de preview (pas de post)
else if (!H::get('refresh')) {
    $type = H::get('type');
    echo H::html(H::link(__("Annuler et afficher la liste"), 'invoice', 'list', ['type' => $type]), 'div')->escape(false)->addCssClass('text-center');
}
