<?php 

use Sma\Bean\InvoiceBean as IB;

$buttons = [
    H::button(__("Devis"), H::url('invoice', 'edit', ['type' => IB::TYPE_QUOTE]))
        ->block()->sizeHuge()->statusInfo()->marginBottom(),
    H::button(__("Commande"), H::url('invoice', 'edit', ['type' => IB::TYPE_ORDER]))
        ->block()->sizeHuge()->statusInfo()->marginBottom(),
    H::button(__("Facture"), H::url('invoice', 'edit', ['type' => IB::TYPE_INVOICE]))
        ->block()->sizeHuge()->statusInfo()->marginBottom(),
    H::button(__("Liste des devis"), H::url('invoice', 'list', ['type' => IB::TYPE_QUOTE]))
        ->block()->sizeLarge()->statusInfo()->marginBottom(),
    H::button(__("Liste des commandes"), H::url('invoice', 'list', ['type' => IB::TYPE_ORDER]))
        ->block()->sizeLarge()->statusInfo()->marginBottom(),
    H::button(__("Liste des factures"), H::url('invoice', 'list', ['type' => IB::TYPE_INVOICE]))
        ->block()->sizeLarge()->statusInfo()->marginBottom(),
];
echo H::grid()->auto($buttons, 3);
