## ADMIN : only admins
## PUBLIC : everyone
## LOGGED : logged in users
## NOTLOGGED : not logged in users
## XXX : users in group XXX
## name@host.com : a user

controller: LOGGED
action:
    index:
    home:
    letter:
    template:
    templates:
    tpldetail:
    deletetpl:
    generate:
#    procedure:
#    procedures:
    history:
    delete:
    view:
    export:
    chst:
    send:
    dl: PUBLIC
    