## ADMIN : only admins
## PUBLIC : everyone
## LOGGED : logged in users
## XXX : users in group XXX
## name@host.com : a user

controller: LOGGED
action:
    index:
    edit:
    send:
    list:
    delete:
    preview:
    export:
    newinvoice:
    newquote:
    neworder:
    invoices:
    quotes:
    orders:
    view:
    chst:
    update:
