<?php

//use Osf\View\Helper\Bootstrap\Addon\DropDownMenu;
//
//$params = CT::getRequest()->getParams();
//
//echo H::nav(false, false, true)
//        ->addLink('', H::url('recipient'), false, false, 'home')
//        ->addLink('',   H::url('recipient', 'edit'), false, false, 'plus')
//        ->addMenu('', (new DropDownMenu())->alignRight()
//                ->addLink(__("Nouveau"),     H::url('recipient', 'edit')));
