---
config: 
    priority: 40
i:
  label: Documentation
  icon: book
  params:
    controller: info
  items:
    ia:
      label: Guide
      params:
        action: book
    iap:
      label: A propos
      params:
        action: credits
...
